
workflows:
  flutter-workflow:
    name: Mening CI/CD Dasturim
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter analyze
      - flutter test
      - flutter build apk
    artifacts:
      - build/**/outputs/**/*.apk
